// SPDX-License-Identifier: GPL-3.0-only
// pono_theme.h - Pono Print design token registry
//
// Kukui on glass (the lamp; pono-design canon): warm black,
// one amber lamp, phosphor instrument readouts, mono lettering, hairline
// rules, machined corners. The lamp is light, not paint: it marks the
// action at hand, live attention, and focus. Phosphor marks live numbers.
// Alarm marks faults and destructive actions, nothing else.
//
// Usage:
//   #include "pono_theme.h"
//   lv_obj_set_style_bg_color(my_obj, pono::color_accent_primary, 0);
//   lv_obj_set_style_text_font(label, pono::font_h2, 0);
//
// To install the theme (call once after lv_init() in main.cpp):
//   pono::theme_init(disp);

#pragma once
#include "lvgl.h"

namespace pono {

// ---- Color tokens (Kukui) ----
extern const lv_color_t color_surface_base;     // #0d0b09 the room (warm black)
extern const lv_color_t color_surface_raised;   // #110f0c panel
extern const lv_color_t color_surface_elevated; // #181510 lift (hover/raised)
extern const lv_color_t color_accent_primary;   // #e2a13c the lamp (amber)
extern const lv_color_t color_accent_secondary; // #8fd6ad phosphor (live readouts)
extern const lv_color_t color_state_error;      // #e06a5a alarm (faults only)
extern const lv_color_t color_state_warning;    // #c9923f deep amber (standby/caution)
extern const lv_color_t color_state_intel;      // #6fae8c dim phosphor (secondary instrument)
extern const lv_color_t color_text_primary;     // #e8e2d6 ink (warm paper)
extern const lv_color_t color_text_secondary;   // #928b7c dim
extern const lv_color_t color_text_tertiary;    // #6a6457 faint (labels)

// ---- Border alpha tokens (hairlines: ink at 9% / 18% / 25%) ----
extern const lv_opa_t opa_border_subtle;
extern const lv_opa_t opa_border_medium;
extern const lv_opa_t opa_border_strong;

// ---- Typography tokens ----
// IBM Plex Mono is the instrument lettering: every label, readout, key,
// and numeral. Instrument Serif is the logbook voice, spent on exactly
// two moments: the pono dictionary entry (idle cockpit) and the boot
// dedication + motto. Generated by tools/regen_pono_fonts.sh.
extern const lv_font_t *font_h2;            // 20 Plex Medium (screen titles)
extern const lv_font_t *font_body;          // 14 Plex Regular
extern const lv_font_t *font_caption;       // 12 Plex Medium
extern const lv_font_t *font_micro;         // 10 Plex Medium (letterspaced caps tags)
extern const lv_font_t *font_num_large;     // 32 Plex SemiBold
extern const lv_font_t *font_num_medium;    // 20 Plex SemiBold
extern const lv_font_t *font_num_small;     // 14 Plex Regular
extern const lv_font_t *font_serif_display; // 40 Instrument Serif (the headword)
extern const lv_font_t *font_serif_xl;      // 56 Instrument Serif (boot dedication)
extern const lv_font_t *font_serif_italic;  // 18 Instrument Serif Italic (gloss/motto)

// ---- Spacing tokens ----
constexpr lv_coord_t space_xs = 4;
constexpr lv_coord_t space_sm = 8;
constexpr lv_coord_t space_md = 12;
constexpr lv_coord_t space_lg = 16;
constexpr lv_coord_t space_xl = 24;

// ---- Radii tokens ----
// Machined corners. One value on purpose: rounded cards are banned; 2px is
// the largest radius that still reads square on this 480x272 panel.
constexpr lv_coord_t radius_sm = 2;
constexpr lv_coord_t radius_md = 2;
constexpr lv_coord_t radius_lg = 2;

// ---- Letterspacing (caps tags; LVGL takes px, ~1px at 10-12pt mono) ----
constexpr lv_coord_t track_caps = 1;

// ---- Frame architecture constants ----
constexpr lv_coord_t frame_width   = 480;
constexpr lv_coord_t frame_height  = 272;
constexpr lv_coord_t rail_width    = 48;
constexpr lv_coord_t topbar_height = 28;
constexpr lv_coord_t content_x     = rail_width;
constexpr lv_coord_t content_y     = topbar_height;
constexpr lv_coord_t content_w     = frame_width - rail_width;
constexpr lv_coord_t content_h     = frame_height - topbar_height;

// ---- The E-STOP's corner ----
// The kill switch rides lv_layer_top() over every screen, top-right on the
// 12px outer margin, and its hit area reaches estop_hit past its edge. Nothing
// but a backdrop may sit inside that reach: end left of estop_clear_x or start
// at or below estop_clear_y. sim/pono_headless audits every render for it.
constexpr lv_coord_t estop_w       = 64;
constexpr lv_coord_t estop_h       = 26;
constexpr lv_coord_t estop_x       = frame_width - 12 - estop_w;
constexpr lv_coord_t estop_y       = 10;
constexpr lv_coord_t estop_hit     = 8;
constexpr lv_coord_t estop_clear_x = estop_x - estop_hit;            // 396
constexpr lv_coord_t estop_clear_y = estop_y + estop_h + estop_hit;  // 44

// ---- Motion duration tokens ----
// Hovers/presses instant-to-120ms, entrances 140-240ms ease-out, instruments
// may run continuous. High-frequency actions get zero animation.
constexpr uint32_t motion_fast       = 120;   // button press
constexpr uint32_t motion_base       = 200;   // default fade
constexpr uint32_t motion_slow       = 350;   // screen transition
constexpr uint32_t motion_deliberate = 600;   // boot intro
constexpr uint32_t motion_pulse      = 2000;  // idle pulse cycle

// ---- Init ----
//
// Registers the Pono theme on the given display. Call once after lv_init().
// Idempotent: calling twice replaces the theme on the second call.
void theme_init(lv_disp_t *disp);

// ---- LV_PALETTE_* to Pono token mapping ----
//
// Bridges user-configured int palette indices (LV_PALETTE_RED through
// LV_PALETTE_GREY, plus LV_PALETTE_NONE = 0xff sentinel) to the Kukui
// token cluster. Used by main_panel temp sensor color config where the
// user-supplied int is cast to lv_palette_t.
//
// Out-of-range input returns color_text_tertiary as a safe default; this
// covers LV_PALETTE_NONE + any corrupted config value.
lv_color_t color_for_palette(lv_palette_t p);

// ---- Panel open animation ----
//
// panel_open() moves a panel to the foreground and fades it in from
// transparent (a short ease-out), so overlay panels "open" smoothly instead
// of snapping in. Self-contained and safe to call repeatedly: a re-open
// restarts the fade cleanly. There is intentionally no animated hide here --
// the foreground/background z-order close stays instant (the riskiest part to
// get right blind); 60 fps + the open fade already carry the feel.
void panel_open(lv_obj_t *obj);

} // namespace pono
